### ISSUE TITLE
Version 6.1.0: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module 

### ISSUE THREAD

**Issue by bogdanbeniaminb** [Siilwyn/css-declaration-sorter#185]
Starting with version 6.1.0, we get the following error:
```javascript

ERROR in ../css/theme.css
../css/theme.css from Css Minimizer
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ../src/node_modules/css-declaration-sorter/orders/alphabetical.mjs
    at Module.load (internal/modules/cjs/loader.js:926:11)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ../src/node_modules/css-declaration-sorter/src/main.cjs:313:87
    at async LazyResult.runAsync (../src/node_modules/postcss/lib/lazy-result.js:431:15)
    at async cssnanoMinify (eval at transform (../src/node_modules/css-minimizer-webpack-plugin/dist/minify.js:34:28), <anonymous>:51:18)
    at async minify (../src/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:26)
    at async Object.transform (../src/node_modules/css-minimizer-webpack-plugin/dist/minify.js:35:18)

```

@Siilwyn This is directly related to the refactoring that was done 2 days ago, replacing JSON with .mjs files.

Node version: 14.16.0 (LTS version).

Thank you.

**Comment by Siilwyn** [comment]
Thanks for reporting!

This should be fixed in `6.1.1`, please let me know if it didn't solve your issue.

**Comment by bogdanbeniaminb** [comment]
Thank you for fixing this so shortly! (I've just tested and the issue is now gone.)

**Comment by Siilwyn** [comment]
Happy to help. :+1:
